name: The Zingaro
favicon: null
layout_spectrum: 0.1465500786434859
typography_spectrum: 0.37196766934357584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5422408110462129
  lightness: 0.6233272908721119
  saturation: 0.6364265191368759
  rhythmicContrast: 0.7082239601295441
purpose: []
